Feature/eslint (eslint추가)
xEzIxX/expressTest pull request #18
Opened 2023-12-19 16:23 UTC by xEzIxX

### 1. feature/eslint 브랜치에 eslint 추가
(현재 feature/eslint branch에서는 여기까지 진행하였습니다.)

**1. .eslintignore**
기본적으로 eslint는 node_modules/, dot파일을 무시합니다. 그 외의 파일을 명시해두었습니다.   

> 처음에는 package.json에 "eslintIgnore": ["src/public/**","*.ejs","*.json"]을 이용하여 eslint가 무시할 파일들을 지정하였지만 eslint가 .eslintignore에서 먼저 파일을 찾을 수 없고 대체 파일이 지정되지 않은 경우  package.json의 "eslintIgnore"를 확인하는 것을 고려하여 변경하였습니다.

![.eslintignore파일](https://github.com/xEzIxX/expressTest/assets/128362224/c359fec8-771c-40c3-9aca-1b8b61416c10)

**2. npm run lint**
다음은 package.json파일입니다. script에 "lint": "eslint ."를 추가하여 "npm run lint"명령어 입력시  *.eslintignore에 명시된 파일을 제외한 모든 파일*을 eslint를 사용하여 문법에 에러가 있는 곳을 알 수 있습니다.
![전체 파일 검사를 위한 lint명령어 추가](https://github.com/xEzIxX/expressTest/assets/128362224/0a8ae24b-e8a3-4248-b2fa-251a851183d9)

### 2. feature/prettier 브랜치에 prettier 추가
_(12/20)_

### 3. eslint와 prettier를 함께 사용하기 위한 모듈 추가
3-1. eslint와 prettier의 충돌을 방지하기 위해 .eslintrc.js파일에서 extends;['airbnb-base', 'prettier'] 추가
_(12/20)_

2023-12-19 23:33 UTC, Mangcho commented
작은 1, 2번을 합칠 수 있다고 생각합니다
eslintignore 없이도 스크립트만으로 할 수 있어요

2023-12-19 23:35 UTC, Mangcho commented
그리고 프리티어 관련 내용은 여기 적지 말아주세요
다시한번.. 우리 브랜치 만든 이유가 있잖아요..ㅠ

2023-12-19 23:38 UTC, Mangcho reviewed
재수정!

2023-12-21 15:23 UTC, Mangcho requested changes
1. Rule
2. 프리티어와의 통합

두개 고민하시고 알려주세요

2023-12-21 15:23 UTC, Mangcho commented on .eslintrc.cjs
> +  rules: {
프리티어 관련 세팅이 필요할거 같은데요? 
어떻게 처리하실 생각이신가요?

2023-12-22 04:50 UTC, Mangcho approved these changes
이륙하셔도 될것같아요

2023-12-23 13:37 UTC, xEzIxX commented
@Mangcho  이륙.. 그거 어떻게 하는거죠,,, 난...... 갈 수 없는데..... **흙흙!** ~_(자갈 자갈.. 모래... 모래....)_~

2023-12-23 14:48 UTC, merged