Feature/auth
xEzIxX/expressTest pull request #28
Opened 2024-01-01 16:26 UTC by xEzIxX

2024-01-01 16:28 UTC, Mangcho commented on views/loginPage.ejs
EJS는 front branch 쪽으로 바꾸어 올리는 것으로 합시다. 
ejs 없어도 postman을 사용해 테스트 해볼 수 있습니다. (더 나은 방법도 분명 있습니다)

2024-01-01 16:35 UTC, Mangcho requested changes
저도 처음 많이 달렸을땐 슬펐습니다. 고칠게 많았거든요.
리뷰하는 사람으로써 봐도 슬프네요. 내가 공부를 더 해야 알려줄 수 있거든요

하..

2024-01-01 16:35 UTC, Mangcho commented on src/routers/login.js
> +    .get(login)
.get(login) 
login이 함수같기는 한데요.. 뭔가 이상함을 느끼시지 않나요?

2024-01-01 16:35 UTC, Mangcho commented on views/loginPage.ejs
EJS는 front branch 쪽으로 바꾸어 올리는 것으로 합시다. 
ejs 없어도 postman을 사용해 테스트 해볼 수 있습니다. (더 나은 방법도 분명 있습니다)

2024-01-01 16:35 UTC, Mangcho commented on src/services/login.js
함수 하나하나로 작성하지 마시고, 클래스를 사용해서 작성해 봅시다.
한번에 export 할 수 있도록 하기 위해서요

2024-01-01 16:35 UTC, Mangcho commented on src/routers/login.js
> +export default router;
default 문 대신 일반 export로 대체해주세요
차이점을 모르신다면 esm / cjs의 차이에 대해 issue로 적고 여기 태그해주세요.
태그 방법도 모르신다구요?  그것도..

2024-01-02 08:22 UTC, Mangcho commented on src/routers/login.js
> +router.route('/logout')
이거는 무언가 잘못된거 같은데요? 다시 확인해보세요

2024-01-02 08:23 UTC, Mangcho commented on src/app.js
> +app.use('/login', loginRouter);
이게 맞을까요..?

2024-01-02 10:04 UTC, xEzIxX commented on src/routers/login.js
> +export default router;
default문과 일반 export문의 차이점이 먼저 궁금하여서 [export issue](https://github.com/xEzIxX/expressTest/issues/29#issue-2062177879)와 같은 이슈 작성을 선행하였습니다.. esm / cjs의 차이에 대한 이슈도 이어서 적겠습니다!

2024-01-02 10:05 UTC, Mangcho commented on src/routers/login.js
> +export default router;
#29 이게 태그입니다

2024-01-02 10:39 UTC, xEzIxX commented on src/app.js
> +app.use('/login', loginRouter);
아니요! routers/login.js에서 모듈을 export {router}로 내보냈기 때문에 loginRouter을 router로 수정하거나  routers/login.js 파일의 router를 loginRouter로 수정해야 할 것 같습니다..!! 

저는 routers/login.js 파일의 router를 loginRouter로 수정하겠습니다!!!!

2024-01-02 10:51 UTC, xEzIxX commented on src/routers/login.js
> +router.route('/logout')
힌트...🥲 혹시.. 안될까요.....?🥲🥲🥲🥲🥲

2024-02-04 05:05 UTC, Mangcho requested changes
작성한 댓글을 보고 고민하고 다시 작업부탁드려요

2024-02-04 05:05 UTC, Mangcho commented on src/utils/jwt.js
굳이 클래스로 둬야할 필요가 있었을까 싶긴 하네요.

2024-02-04 05:05 UTC, Mangcho commented on src/services/auth.js
> +            } else {
undefined가 나올것 같지는 않은디,. 
좀 더 정확하게 else if로 조건을 주는게 좋을거 같습니다

2024-02-04 05:05 UTC, Mangcho commented on src/services/auth.js
> +    async login(user_email, password) {
Dto로 받아오세요.

2024-02-04 05:05 UTC, Mangcho commented on src/routers/auth.js
> +            const { accessToken } = await authService.login(  // tk 발급
Dto로 받아오세요

2024-02-04 05:05 UTC, Mangcho commented on src/services/auth.js
> +    async signUp(newUserDto) {
비밀번호 비교 로직은 어디에 있을까요?
비번1 비번2 입력받아 비교하는 로직이요

2024-02-04 05:05 UTC, Mangcho commented on src/utils/crypto.js
파일명을 getHash나 다른것으로 바꿔주세요
crypto-js라는 모듈이 있어서 헷갈릴것 같아요 
[npmjs](https://www.npmjs.com/package/crypto-js)

2024-02-06 04:45 UTC, Mangcho approved these changes
수정사항 확인해주세요

2024-02-06 04:45 UTC, Mangcho commented on src/services/auth.js
로그인 실패 케이스는 throw 말고...
return은 해주셔야 할것 같아요

2024-02-06 04:45 UTC, Mangcho commented on src/routers/auth.js
> +                res.status(404).send(isCreated)
로그인 실패도 이런것처럼 처리해주세요

2024-02-06 04:45 UTC, Mangcho commented on src/services/auth.js
> +            } else if (user === undefined) { // 비정상적인 case
undefined는 예시일 뿐이었습니다..

2024-02-14 14:43 UTC, Mangcho requested changes
코멘트 확인해주세요

2024-02-14 14:43 UTC, Mangcho commented on package.json
> +    "node-fetch": "^3.3.2",
왜 추가했을까요?

2024-02-14 14:43 UTC, Mangcho commented on src/routers/auth.js
> +    return res.render('login.ejs')
ejs는 엄청 많아질것 같은데, 디렉토리를 좀 더 추가해서 구분하는게 어떨까요?

2024-02-14 14:43 UTC, Mangcho commented on src/routers/auth.js
> +                throw err
이건 왜있는거죠?
검증하셨을까요?

2024-02-14 14:43 UTC, Mangcho commented on src/routers/auth.js
> +                throw err
동일합니다

2024-02-14 14:43 UTC, Mangcho commented on src/routers/auth.js
> +        return res.render('sign.ejs')
동일합니다

2024-02-14 14:43 UTC, Mangcho commented on src/routers/auth.js
> +        return res.render('sign.ejs')
추가로, res.render와 ejs.render의 차이점이 뭘까요?

2024-02-14 14:43 UTC, Mangcho commented on src/routers/auth.js
> +                return res.send('로그아웃') /// 'auth/login' 경로로 이동
왜 res.send를 사용하셨을까요? 
그리고 사용하셨다면 어떻게 auth/login으로 이동할까요?

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +            if (user instanceof db.User) {
어디서 이걸 찾으셨을까요?
그냥 궁금해서요

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +                throw err
이것도 동일한 문제입니다. 
분명 구두로 알려드린 부분에서 동일한 문제가 발생하는건 이해하기 어렵네요

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +                const foundCreated = await db.User.findOne({
foundCreated의 의도가 뭔가요?
찾았다 생성했다
뭘까요..

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +                    throw err
동일합니다.

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +                    return { result: true, message: '회원가입' }
얘는 message가 회원가입인데
아래는 회원가입 중 회원정보 저장 실패네요 뭘까요

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +                } else falseMessage = '중복된 닉네임과 이메일'
일관성 있게 했으면 좋겠지만..
일단은 이렇게라도 해둡시다

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +                jwt.verify(accessToken, process.env.SECRET_KEY) // 유효하지 않으면 throw err
만들자마자 검증하는 이유는?

2024-02-14 14:43 UTC, Mangcho commented on src/services/auth.js
> +                const accessToken = newToken(user.user_id, user.user_nickname)
사실 저라면 하나의 객체로 밀어서 넣어줬을거 같은데.. 두개로 따로 하지 않고
이건 취향차인것 같으니 따로 수정안하셔도 됩니다. 정답도 잘 모르겠어요 솔직히

2024-02-14 14:43 UTC, Mangcho commented on src/routers/auth.js
> +            const isToken = !(
의미가 뭘까요?
이렇게 없는 것을 다 증명하려고 시도할 필요가 있나 싶은데

2024-02-15 14:07 UTC, xEzIxX commented on src/routers/auth.js
> +    return res.render('login.ejs')
views디렉토리에 하위 디렉토리인 auth를 추가하여 로그인/회원가입 ejs를 넣어두었습니다. app.js파일의 app.set('views', './src/views')에서 기본 경로를  ./src/views로 설정해두었기 때문에 경로를 auth/login.ejs 로 수정하였습니다.

2024-02-15 14:11 UTC, xEzIxX commented on package.json
> +    "node-fetch": "^3.3.2",
nodejs에서 fetch를 사용하기 위해서는 따로 모듈이 필요하다고 하여 추가하였으나, 정작 fetch를 사용하는 것은 ejs 파일의 <script>태그에서 js를 사용하였기 때문에 해당 모듈을 삭제하였습니다..

2024-02-15 14:25 UTC, xEzIxX commented on src/services/auth.js
> +            if (user instanceof db.User) {
[ 'Model Instances' - Creating an instance](https://sequelize.org/docs/v6/core-concepts/model-instances/), [ 'Model Querying - Finders' - findByPk, findOne ](https://sequelize.org/docs/v6/core-concepts/model-querying-finders/) 에서 인스턴스를 생성하거나 찾은 후 console.log(project instanceof Project)로 확인하는 코드를 보고 사용했습니다..!

2024-02-15 14:29 UTC, xEzIxX commented on src/services/auth.js
> +                    return { result: true, message: '회원가입' }
각각 '회원가입 완료/ 회원가입 실패'로 수정하였습니다

2024-02-15 14:34 UTC, xEzIxX commented on src/services/auth.js
> +                jwt.verify(accessToken, process.env.SECRET_KEY) // 유효하지 않으면 throw err
서비스함수에서 발급하고 토큰을 반환하는데, 이 때 반환되는 토큰이 유효한지 확인하기 위해 바로 검증하였습니다..

2024-02-15 14:41 UTC, xEzIxX commented on src/routers/auth.js
> +            const isToken = !(
헤더에 토큰이 존재하는지 확인하는 로직을 ```const isToken = Boolean(req.headers.authorization) ``` 로 수정하였습니다

2024-02-15 14:43 UTC, xEzIxX commented on src/services/auth.js
> +                } else falseMessage = '중복된 닉네임과 이메일'
변수명을 falseMessage -> message 로 수정하였습니다..

2024-02-15 14:48 UTC, xEzIxX commented on src/routers/auth.js
> +                throw err
try문의 throw err를 서비스 함수에서는 ```return { result: false, message: '서비스 오류' }```로 , 
라우터에서는 ```return res.status(500).send('서버 오류')``` 로 수정하였습니다 ㅠ

2024-02-16 02:12 UTC, xEzIxX commented on src/services/auth.js
> +                } else falseMessage = '중복된 닉네임과 이메일'
넵!

2024-02-16 04:12 UTC, xEzIxX commented on src/routers/auth.js
> +                return res.send('로그아웃') /// 'auth/login' 경로로 이동
res.send()는 send에 전해진 데이터의 타입에 따라 Content-type이 자동적으로 만들어지는 반면, res.json()은 무조건  json 형식으로 바꾸어서 보내주기 때문에 res.send를 사용하였습니다. ([출처](https://yohanpro.com/posts/nodejs/express-response))

auth/login로의 이동은 프론트에서 fetch메소드를 사용하여 구현할 예정입니다.

2024-02-19 02:27 UTC, xEzIxX commented on src/routers/auth.js
> +        return res.render('sign.ejs')
주요 차이는 다음과 같습니다.
1. ejs.render는 'EJS 템플릿'만을 렌더링하는 반면 res.render는 더 포괄적으로 뷰를 렌더링 합니다.
2. ejs.render는 클라이언트에게 응답하지 않지만 res.render는 클라이언트에게 응답을 합니다.

> - **ejs.render(str, data, options)** 는 문자열(str)로부터 EJS 템플릿을 렌더링합니다.
> - **res.render(view [, locals] [, callback])** 는 뷰를 렌더링하고 렌더링된 HTML 문자열을 클라이언트에게 응답으로 보냅니다. 

> [ 익스프레스에서 템플릿을 렌더링하기 위한 세팅 ]
> 1. app.set('views들이 저장된 디렉토리', '디렉토리 경로')
> 2. app.set('view engine', '사용할 템플릿 엔진')

2024-02-19 03:11 UTC, Mangcho commented on src/routers/auth.js
> +        return res.render('sign.ejs')
@xEzIxX 
1. "포괄적으로"의 의미가 무엇일까요?
2. 둘 중 어떤것을 쓰는게 좋을까요?

2024-02-19 07:04 UTC, xEzIxX commented on src/services/auth.js
> +                jwt.verify(accessToken, process.env.SECRET_KEY) // 유효하지 않으면 throw err
토큰의 유효성 확인과 토큰의 존재를 확인하는 개념을 헷갈려서 사용하였던 코드같습니다. 
유효성을 검증하는 코드는 삭제하고, 대신 다음과 같은 토큰의 존재 여부를 판단하는 코드를 추가하였습니다.

```
               if (Boolean(accessToken) === true) { // access토큰이 정상적으로 발급 되었다면
                    return {
                        result: true,
                        message: '존재하는 회원',
                        token: accessToken,
                    }
                } else { 
                    return {
                        result: false,
                        message: '토큰 발행 오류',
                        token: null,
                    }
                }
            }
```

2024-02-19 09:00 UTC, xEzIxX commented on src/routers/auth.js
> +        return res.render('sign.ejs')
1. res.render는 EJS, Pug, Handlebars(주로 Express에서 사용하는 템플릿 엔진) 등을 렌더링 할 수 있지만, ejs.render는 오직 ejs만 가능하기 때문에 "포괄적으로"라는 용어를 사용하였습니다.
2. ejs.render를 사용한다면 사용자에게 응답하는 과정을 한 번 더 거쳐야하기 때문에 res.render를 사용하기 것이 더 좋다고 생각합니다.

2024-02-19 10:04 UTC, Mangcho approved these changes
EJS는 따로 안봤습니다.
이젠 시간이 없으니 통합합시다

2024-02-19 10:04 UTC, Mangcho commented on src/routers/auth.js
> +        return res.render('auth/sign.ejs')
이런건 서비스가 필요없는게 맞겠죠..?
저도 이건 잘 모르겠음

2024-02-19 10:04 UTC, Mangcho commented on src/routers/auth.js
> +                return res.status(500).send({ message: '로그아웃 실패' })
이 경우엔 else가 생길 수 없겠죠. Boolean의 결과는 t or f니까

2024-02-19 10:04 UTC, Mangcho commented on src/services/auth.js
> +            if (user instanceof db.User) {
이중 if문은 가독성을 떨어뜨리게 됩니다.
하지만.. 우린 바쁘니까..

2024-02-19 10:08 UTC, xEzIxX commented on src/routers/auth.js
> +                return res.status(500).send({ message: '로그아웃 실패' })
바로 수정하겠습니다..! 함수 결과 자체가 t/f로만 나오는지 그 예외의 경우가 발생할 수 있는지 함수의 결과를 주의깊게 보도록 하겠습니다..

2024-02-19 10:21 UTC, merged