[ Sequelize ] User, Board, Comment 테이블 생성 및 데이터 베이스와 연동
xEzIxX/expressTest pull request #34
Opened 2024-01-16 01:27 UTC by xEzIxX

## 목적 
테이블 생성 및 데이터 베이스와 연동

## 추가 내용

1. 현재 ERD에 정의된 테이블을 mysql에 생성하기 위하여 우선 models 디렉토리에 User, Board, Comment 모델 인스턴스를 정의하였습니다.
2. index.js파일에서 1과 같이 정의된 모델 인스턴스를 데이터베이스에 연동시켜 테이블을 생성하고, 테이블 간 관계를 정의하였습니다.(hasMany, belongsTo)
3. app.js에서는 loaders/sequelize.js파일에서 정의한 함수 sequelizeLoader를 불러와 데이터 베이스 연결/ 동기화 성공 여부를 확인합니다.

## 특이사항

1. 모델 인스턴스를 정의하는 파일에서 시퀄라이즈 객체를 import해오는 것이 아닌 매개변수를 전달 받는 방식을 사용하였습니다. 

2. 모델 인스턴스의 id의 데이터 타입을 UUID로 설정하였습니다. (다음은 user 객체의 예시입니다.)
```
user_id: {
                type: DataTypes.UUID,
                defaultValue: DataTypes.UUIDV4,
                primaryKey: true,
                allowNull: false,
            },
```

3. FK 칼럼(board_user_id, comment_user_id, comment_board_id)에는 field, references 속성을 더 추가하였습니다.

- field : 데이터베이스 테이블에서 사용될 필드의 이름
- references : 참조되는 모델의 이름(model)과 참조되는 모델의 컬럼 이름(key)을 정의

2024-01-16 01:54 UTC, Mangcho requested changes
수정^^

2024-01-16 01:54 UTC, Mangcho commented on src/loaders/sequelize.js
3번째 줄 선언과 15번째 줄 export를 합칠 수 있을까요

2024-01-16 01:54 UTC, Mangcho commented on src/models/index.js
> +import { Sequelize } from 'sequelize'
어차피 매개변수로 던져줄거라면 Datatypes도 여기서 같이 주는게 좋을거 같아요. 모델마다 import 따로 하지 말고

2024-01-16 01:54 UTC, Mangcho commented on src/models/comment.js
> +import { DataTypes } from 'sequelize'
index.js 리뷰 참고

2024-01-16 01:54 UTC, Mangcho commented on src/models/board.js
> +import { DataTypes } from 'sequelize'
index.js 리뷰 참고

2024-01-16 01:54 UTC, Mangcho commented on src/models/index.js
> +        dialect: process.env.DB_DIALECT,
dialect 말고 다른 옵션들이 생긴다면 어떻게 추가하실 건가요?
development와 production에 따른 차이는요?

2024-01-16 01:54 UTC, Mangcho commented on src/models/user.js
> +import { DataTypes } from 'sequelize'
index.js 리뷰 참고

2024-01-16 01:54 UTC, Mangcho commented on src/routers/auth.js
여긴 따로 안볼게요

2024-01-16 01:54 UTC, Mangcho commented on src/services/auth.js
동일하게 안봅니다

2024-01-16 02:49 UTC, xEzIxX commented on src/models/index.js
> +        dialect: process.env.DB_DIALECT,
config/config.json 파일 정의를 통해 해결 하겠습니다! (수정중입니다!)

2024-01-16 02:50 UTC, xEzIxX commented on src/models/index.js
> +import { Sequelize } from 'sequelize'
넵!!!!!!

2024-01-17 06:52 UTC, Mangcho requested changes
envSet() 함수의 위치가 저기에 있다면, 정상적으로 다른 env를 불러오는 함수들이 작동하나요? 확인부탁드려요

2024-01-17 06:52 UTC, Mangcho commented on src/utils/envset.js
파일명이랑 함수명이 구려요

2024-01-17 06:53 UTC, xEzIxX commented on src/utils/envset.js
진짜요?ㅠㅠㅜㅠㅜㅠㅜㅠㅜㅠㅜㅠㅜㅠ

2024-01-17 07:14 UTC, xEzIxX commented on src/utils/envset.js
다른 env를 불러오는 함수들은 정상적으로 작동합니다! console.log(process.env.DB_NAME)를 통해서 envSet()가 사용된 models/index.js파일과 app.js에서 확인했습니다!

2024-01-17 07:15 UTC, xEzIxX commented on src/models/index.js
> +        dialect: process.env.DB_DIALECT,
일단, development와 production에 따른 차이는 .env파일을 .env.dev파일, .env.prod파일로 분리하여 해결하였습니다!

2024-01-18 02:58 UTC, Mangcho approved these changes

2024-01-18 06:16 UTC, Mangcho requested changes
다음 요청시에는 실행되는지 확인하시고, 조금 더 생각하고 요청하셨으면 좋겠습니다

2024-01-18 06:16 UTC, Mangcho commented on .gitignore
.env를 따로쓰기보다는 *를 활용해서 적어주세요

2024-01-18 06:16 UTC, Mangcho commented on src/config/sequelize.js
dotenv.config를 통해 이미 env 파일을 지정해주었다면, 굳이 같은 config 내용을 두 번 쓸 필요가 있을까요

2024-01-18 06:16 UTC, Mangcho commented on src/app.js
이게 실행이 되나요? 작동할거 같지 않은데

2024-01-18 06:16 UTC, Mangcho commented on src/models/index.js
config를 함수로써 구성하셨다면, 굳이 같은 함수를 여러번 실행할 필요가 있을까요?
return 값을 받아와서 객체 하나로 구성해도 될것 같은데요

2024-01-19 09:34 UTC, xEzIxX commented on .gitignore
넵!!

2024-01-19 09:38 UTC, Mangcho commented on src/app.js
> +    //console.log('********************** app.js test :', process.env.NODE_ENV, process.env.DB_NAME, '**********************')
이건 테스트 코드가 아닙니다 지워주세요

2024-01-19 09:38 UTC, Mangcho commented on src/config/env.js
> +const path = process.env.NODE_ENV === 'development' ? '.env.dev' : '.env.prod'
실수로 NODE_ENV가 a로 설정된다면 무조건 프로덕션 환경으로 가겠죠?

2024-01-19 09:39 UTC, Mangcho commented on src/models/index.js
> +console.log('********************** models/index.js :', process.env.NODE_ENV, process.env.DB_NAME, config.database, '**********************')
이러한 콘솔 로그는 필요 없습니다.
테스트의 일환이라면 이건 테스트가 아닙니다

2024-01-19 09:42 UTC, xEzIxX commented on src/app.js
> +    //console.log('********************** app.js test :', process.env.NODE_ENV, process.env.DB_NAME, '**********************')
넵!!!

2024-01-19 10:37 UTC, merged